[package]
name = "vm"
version = "0.1.0"
authors = ["lausek <root@lausek.eu>"]
edition = "2018"

[[bin]]
name = "lovm"
path = "src/bin.rs"

[dependencies]
lovm = { path = "../." }
lovm-asm = { path = "../asm" }
